APP-24380: Add `useBreadcrumb` prop on `NavBar` to add collapse feature
habx/lib-design-system pull request #2086
Opened 2021-10-19 13:33 UTC by habxtech

2021-10-19 13:45 UTC, jean9696 requested changes

2021-10-19 13:45 UTC, jean9696 commented on src/NavBar/NavBar.interface.ts
> +  useBreadcrumb?: boolean
Can we change the prop name to something more generic like `collapsable` ? @alexisfontaine what do you think ?

2021-10-19 13:45 UTC, jean9696 commented on src/NavBar/NavBar.style.ts
> +  &[data-useBreadcrumb='true'] {
```suggestion
  &[data-useBreadcrumb='true']:not([data-expanded='true']) {
```

2021-10-19 13:45 UTC, jean9696 commented on src/NavBar/NavBar.style.ts
> +  &[data-useBreadcrumb='true'] {
Avoid useless brackets

2021-10-19 13:45 UTC, jean9696 commented on src/NavBar/NavBar.style.ts
> +  background-color: white;
Please use theme (in case someday we have a dark mode 😈
```suggestion
  background-color: ${theme.color('background')};
```

2021-10-19 15:00 UTC, Carolinevp commented on src/NavBar/NavBar.style.ts
> +  background-color: white;
I can't use `${theme.color('background')}` as the background set by default is purple/primary?

2021-10-19 15:01 UTC, jean9696 commented on src/NavBar/NavBar.style.ts
> +  background-color: white;
Ah ! Then you can add the param `useRoot` to use the root backgroundColor @Carolinevp

2021-10-20 07:55 UTC, jean9696 approved these changes

2021-10-20 07:58 UTC, merged