Add `SidePanel` in Design System
habx/lib-design-system pull request #2388
Opened 2022-08-22 10:18 UTC by habxtech

2022-08-29 13:58 UTC, jean9696 requested changes

2022-08-29 13:58 UTC, jean9696 commented on src/SidePanel/SidePanel.interface.ts
> +  title: string
Why `title` is required ?

2022-08-29 13:58 UTC, jean9696 commented on src/SidePanel/SidePanel.stories.tsx
> +const Container = styled.div`
I think we should use `Background` here

2022-08-29 13:58 UTC, jean9696 commented on src/SidePanel/SidePanel.stories.tsx
> +  &[data-open='true'] {
Why do you take the whole space for a **side** panel ? Plus, I think we should add an animation for the entrance

2022-08-29 13:58 UTC, jean9696 commented on src/SidePanel/SidePanel.stories.tsx
> +  z-index: 101;
Please use the `zIndex` constant

2022-08-29 13:58 UTC, jean9696 commented on src/SidePanel/SidePanel.tsx
> +}) => {
I think that this component should have the same API than the `Modal` & `Lighbox` and use `useModal`

2022-08-30 08:31 UTC, Carolinevp commented on src/SidePanel/SidePanel.interface.ts
> +  title: string
There is no option without title in the [Figma](https://www.figma.com/file/PM3oYKBDgKXsdRds0tcJ5a/%F0%9F%A7%A9----Slide-Panel?node-id=1%3A106) so I figured it was mandatory

2022-09-30 09:29 UTC, jean9696 approved these changes

2022-09-30 09:30 UTC, merged